### ISSUE TITLE
What would be the best way to store these data?

### ISSUE THREAD

**Issue by iSyn** [iSyn/More_Ore#3]
![screen shot 2016-12-13 at 10 34 06 am](https://cloud.githubusercontent.com/assets/8594833/21146473/c4197714-c11f-11e6-8ce8-e61213a41153.png)

What would be the best way to store these values locally without needing user auth.

I want it so when the browser loads, if the user has been on this site before, it can pull the data from that and load all the values back in...

@gittheking @trevorpreston @jasonseminara @rapala61 @irwintsay

**Comment by rapala61** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by iSyn** [comment]
@rapala61 thanks!
